### ISSUE TITLE
Cypress badge not available

### ISSUE THREAD

**Issue by Heriberto-Juarez** [henriquesebastiao/badges#1]
It would be cool to have a badge for cypress

**Comment by henriquesebastiao** [comment]
Something like this?

https://img.shields.io/badge/Cypress-69D3A7?style=flat&logo=cypress&logoColor=white

![](https://img.shields.io/badge/Cypress-69D3A7?style=flat&logo=cypress&logoColor=white)

https://img.shields.io/badge/Cypress-69D3A7?style=flat&logo=cypress&logoColor=black

![](https://img.shields.io/badge/Cypress-69D3A7?style=flat&logo=cypress&logoColor=black)

**Comment by henriquesebastiao** [comment]
I haven't found anything in the Badges.io documentation that says how to change the color of the text on the right 🥲.

**Comment by Heriberto-Juarez** [comment]
Yes something like that

**Comment by Heriberto-Juarez** [comment]
found it
